/* Google Sheet ID is already configured. The first row should contain headers. */
const SHEET_ID = '1rZx6B94LOAUbwpgrLJmNTmWSzvE3DGOaMTR4GXFzoMo';
// Google Sheets does not allow cross-origin fetches. JSONP lets this static
// file read a public sheet, including when it is opened directly from disk.
const endpoint = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json;responseHandler:sheetCallback`;
const $ = (s) => document.querySelector(s);
let figures = [], exchangeRates = {EUR:1}, ratesReady = false, totalCurrency = localStorage.getItem('minifig-total-currency') || 'EUR', selected = new Set(JSON.parse(localStorage.getItem('minifig-owned') || '[]')), wished = new Set(JSON.parse(localStorage.getItem('minifig-wished') || '[]')), removedOwned = new Set(JSON.parse(localStorage.getItem('minifig-not-owned') || '[]')), removedWished = new Set(JSON.parse(localStorage.getItem('minifig-not-wished') || '[]'));
const clean = v => String(v ?? '').trim();
const column = (row, names) => { for (const name of names) { const key = Object.keys(row).find(k => k.toLowerCase().replace(/[^a-z0-9]/g,'') === name); if(key && row[key] != null) return clean(row[key]); } return ''; };
const num = value => Number(String(value).replace(/[^0-9.,]/g,'').replace(',','.')) || 0;
const currencyCode = value => {const currency=clean(value).toUpperCase();return ({EURO:'EUR','€':'EUR',DOLLAR:'USD',DOLLARS:'USD','US DOLLAR':'USD','$':'USD',POUND:'GBP',POUNDS:'GBP','£':'GBP',YEN:'JPY','¥':'JPY',RMB:'CNY'})[currency] || currency || 'EUR';};
const currencySymbol = value => ({EUR:'€',USD:'$',GBP:'£',JPY:'¥',CNY:'¥',CAD:'C$',AUD:'A$',CHF:'CHF'})[currencyCode(value)] || currencyCode(value);
function imageSource(url){const drive=url.match(/drive\.google\.com\/file\/d\/([^/?]+)/);return drive?`https://drive.google.com/thumbnail?id=${drive[1]}&sz=w1000`:url;}
const FALLBACK_IMAGE = imageSource('https://drive.google.com/file/d/1qMpHMwEFsa2AWsxOdV23iCPu3ZYxG0ES/view?usp=sharing');
function mapRows(rows){ return rows.map((r,i) => { const valueText=column(r,['value','price','worth','estimatedvalue','estvalue']); const collection=column(r,['owned','collectionstatus','collection','availability']).toLowerCase(); const currency=currencyCode(column(r,['currency','currencycode','curr']) || (valueText.toLowerCase().includes('usd')||valueText.includes('$')?'USD':'EUR')); return { id:column(r,['id','number','setnumber','figureid']) || `figure-${i}`, name:column(r,['name','figurname','title']) || `Untitled figure ${i+1}`, character:column(r,['character']), brand:column(r,['brand','maker','company','theme']) || 'Unbranded', origin:column(r,['origin','seller','source']), value:num(valueText), currencyCode:currency, currency:currencySymbol(currency), condition:column(r,['condition','status'])?.toLowerCase() || 'Unknown', collection, tags:column(r,['tags','tag','category','categories']).split(/[,;|]/).map(clean).filter(Boolean), image:column(r,['imageurl','photourl','thumbnail','thumb','picture']), notes:column(r,['notes','description','details','comments']), raw:r }; }); }
function googleRows(payload){const labels=payload.table.cols.map(c=>c.label||c.id);return payload.table.rows.map(row=>Object.fromEntries(labels.map((name,i)=>[name,row.c[i]?.v ?? ''])));}
function showLoadError(err){$('#resultCount').textContent='Could not load the Google Sheet';$('#empty').hidden=false;$('#empty h2').textContent='Catalogue unavailable';$('#empty p').textContent='Check that the sheet is public and its first row has column headings.';$('#resetEmpty').hidden=true;console.error(err)}
function load(){window.sheetCallback=json=>{try{figures=mapRows(googleRows(json));if(!figures.length)throw Error('No rows');renderFilters();render();loadExchangeRates();}catch(err){showLoadError(err)}};const script=document.createElement('script');script.src=endpoint;script.onerror=()=>showLoadError(new Error('Sheet request failed'));document.head.append(script);}
async function loadExchangeRates(){const codes=[...new Set(figures.map(f=>f.currencyCode).concat('USD'))].filter(code=>code!=='EUR');const cached=JSON.parse(localStorage.getItem('minifig-exchange-rates')||'null');if(cached?.rates){exchangeRates={EUR:1,...cached.rates};ratesReady=true;updateStats()}if(!codes.length)return;try{const response=await fetch(`https://api.frankfurter.dev/v2/rates?base=EUR&quotes=${codes.join(',')}`);if(!response.ok)throw Error('Exchange-rate request failed');const data=await response.json();exchangeRates={EUR:1,...Object.fromEntries(data.map(item=>[item.quote,item.rate]))};ratesReady=true;localStorage.setItem('minifig-exchange-rates',JSON.stringify({rates:exchangeRates,updated:Date.now()}));updateStats()}catch(err){console.warn('Using cached or unconverted currency values',err)}}
function money(n,c='€'){return n ? `${n.toLocaleString('en-US',{maximumFractionDigits:0})} ${c}` : '—';}
function persist(){localStorage.setItem('minifig-owned',JSON.stringify([...selected]));localStorage.setItem('minifig-wished',JSON.stringify([...wished]));localStorage.setItem('minifig-not-owned',JSON.stringify([...removedOwned]));localStorage.setItem('minifig-not-wished',JSON.stringify([...removedWished]));}
function renderFilters(){const brands=[...new Set(figures.map(f=>f.brand))].sort();const tags=[...new Set(figures.flatMap(f=>f.tags))].sort();$('#brandFilters').innerHTML=brands.map(b=>`<label><input type="checkbox" class="brand-filter" value="${escapeHtml(b)}"> ${escapeHtml(b)}</label>`).join('');$('#tagFilters').innerHTML=tags.map(t=>`<label><input type="checkbox" class="tag-filter" value="${escapeHtml(t)}"> ${escapeHtml(t)}</label>`).join('');document.querySelectorAll('.filters input').forEach(i=>i.addEventListener('change',render));}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
function isOwned(f){return selected.has(f.id)||(!removedOwned.has(f.id)&&['owned','purchased'].includes(f.collection))}
function isWished(f){return wished.has(f.id)||(!removedWished.has(f.id)&&f.collection==='wishlist')}
function statusLabel(f){return f.condition ? f.condition.replace(/\b\w/g,c=>c.toUpperCase()) : 'Unknown'}
function toggleOwned(f){const active=isOwned(f);if(!confirm(`${active?'Remove':'Mark'} “${f.name}” ${active?'from':'as'} owned?`))return false;active?(selected.delete(f.id),removedOwned.add(f.id)):(removedOwned.delete(f.id),selected.add(f.id));persist();render();return true}
function toggleWished(f){const active=isWished(f);active?(wished.delete(f.id),removedWished.add(f.id)):(removedWished.delete(f.id),wished.add(f.id));persist();render();return true}
function filtered(){const query=$('#search').value.toLowerCase();const brands=[...document.querySelectorAll('.brand-filter:checked')].map(x=>x.value);const tags=[...document.querySelectorAll('.tag-filter:checked')].map(x=>x.value);const states=[...document.querySelectorAll('.state-filter:checked')].map(x=>x.value);const conditions=[...document.querySelectorAll('.condition-filter:checked')].map(x=>x.value);let out=figures.filter(f=>{const hay=[f.name,f.character,f.brand,f.origin,...f.tags].join(' ').toLowerCase();const conditionMatch=!conditions.length||(conditions.includes('new')&&f.condition==='new')||(conditions.includes('used')&&f.condition!=='new');return (!query||hay.includes(query))&&(!brands.length||brands.includes(f.brand))&&(!tags.length||tags.some(t=>f.tags.includes(t)))&&conditionMatch&&(!states.length||(states.includes('owned')&&isOwned(f))||(states.includes('wishlist')&&isWished(f)));});const sort=$('#sort').value;return out.sort((a,b)=>sort==='value-desc'?b.value-a.value:sort==='value-asc'?a.value-b.value:sort==='brand'?a.brand.localeCompare(b.brand):a.name.localeCompare(b.name));}
function render(){const items=filtered();const template=$('#cardTemplate');const catalogue=$('#catalogue');catalogue.replaceChildren();items.forEach(f=>{const card=template.content.cloneNode(true);const root=card.querySelector('.card'), img=card.querySelector('img'),hasImage=!!f.image;root.querySelector('h2').textContent=f.name;root.querySelector('.brand').textContent=f.brand;root.querySelector('.price').textContent=money(f.value,f.currency);root.querySelector('.condition').textContent=statusLabel(f); if(!f.collection&&f.condition==='unknown')root.querySelector('.condition').hidden=true;img.src=hasImage?imageSource(f.image):FALLBACK_IMAGE;img.alt=hasImage?f.name:'No figure photo available';img.classList.toggle('fallback-image',!hasImage);img.onerror=()=>{if(!img.classList.contains('fallback-image')){img.src=FALLBACK_IMAGE;img.alt='No figure photo available';img.classList.add('fallback-image')}else img.style.display='none'};const own=root.querySelector('.own'),wish=root.querySelector('.wish');own.classList.toggle('selected',isOwned(f));wish.classList.toggle('selected',isWished(f));own.setAttribute('aria-pressed',isOwned(f));wish.setAttribute('aria-pressed',isWished(f));root.querySelector('.image-button').setAttribute('aria-label',`View details for ${f.name}`);own.onclick=e=>{e.stopPropagation();toggleOwned(f)};wish.onclick=e=>{e.stopPropagation();toggleWished(f)};root.querySelector('.image-button').onclick=()=>openDetail(f);catalogue.append(card)});$('#resultCount').textContent=`${items.length} of ${figures.length} figures`;$('#empty').hidden=!!items.length;$('#resetEmpty').hidden=false;updateStats();const filters=document.querySelectorAll('.filters input:checked').length;$('#filterCount').textContent=filters?`(${filters})`:'';$('#clearFilters').hidden=!filters;}
function updateStats(){const owned=figures.filter(isOwned), needsRates=owned.some(f=>f.currencyCode!=='EUR')||totalCurrency!=='EUR';let value='—';if(!needsRates||ratesReady){const totalEur=owned.reduce((total,f)=>{const rate=exchangeRates[f.currencyCode];return rate?total+(f.value/rate):total},0);const converted=totalEur*(exchangeRates[totalCurrency]||1);value=money(converted,currencySymbol(totalCurrency))}else value='Converting…';$('#totalCount').textContent=figures.length;$('#ownedStat').textContent=owned.length;$('#wishStat').textContent=figures.filter(f=>isWished(f)&&!isOwned(f)).length;$('#ownedValue').textContent=value+(value==='Converting…'?'':' estimated');$('#brandStat').textContent=new Set(figures.map(f=>f.brand)).size;document.querySelectorAll('.currency-toggle button').forEach(button=>{const active=button.dataset.currency===totalCurrency;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active)})}
//function openDetail(f){const image=f.image?`<img src="${escapeHtml(imageSource(f.image))}" alt="${escapeHtml(f.name)}">`:'<span class="placeholder">MINIFIG</span>';$('#detailContent').innerHTML=`<div class="detail-grid"><div class="detail-image">${image}</div><div class="detail-copy"><h2>${escapeHtml(f.name)}</h2><p class="detail-brand">${escapeHtml(f.brand)}</p><div class="detail-tags">${f.tags.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><p class="detail-meta"><b>Character</b> · ${escapeHtml(f.character || '—')}<br><b>Condition</b> · ${escapeHtml(statusLabel(f))}<br><b>Value</b> · ${money(f.value,f.currency)}<br><b>Origin</b> · ${escapeHtml(f.origin || '—')}<br>${escapeHtml(f.notes || '')}</p><div class="detail-actions"><button id="detailOwn">${isOwned(f)?'Owned ✓':'Mark owned'}</button><button id="detailWish">${isWished(f)?'Wishlisted ♡':'Add to wishlist'}</button></div></div></div>`;$('#detail').showModal();$('#detailOwn').onclick=()=>{if(toggleOwned(f)){$('#detail').close();openDetail(f)}};$('#detailWish').onclick=()=>{if(toggleWished(f)){$('#detail').close();openDetail(f)}};}
function openDetail(f){const hasImage=!!f.image;const image=`<img class="${hasImage?'':'fallback-image'}" src="${escapeHtml(hasImage?imageSource(f.image):FALLBACK_IMAGE)}" alt="${escapeHtml(hasImage?f.name:'No figure photo available')}">`;$('#detailContent').innerHTML=`<div class="detail-grid"><div class="detail-image">${image}</div><div class="detail-copy"><h2>${escapeHtml(f.name)}</h2><p class="detail-brand">${escapeHtml(f.brand)}</p><div class="detail-tags">${f.tags.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><p class="detail-meta"><b>Character</b> · ${escapeHtml(f.character || '—')}<br><b>Origin</b> · ${escapeHtml(f.origin || '—')}<br><b>Condition</b> · ${escapeHtml(statusLabel(f))}<br><b>Value</b> · ${money(f.value,f.currency)}<br>${escapeHtml(f.notes || '')}</p><div class="detail-actions"><button id="detailOwn"><span class="material-symbols-rounded">check</span>${isOwned(f)?'Owned':'Mark owned'}</button><button id="detailWish"><span class="material-symbols-rounded">favorite</span>${isWished(f)?'Wishlisted':'Add to wishlist'}</button></div></div></div>`;$('#detail').showModal();$('#detailOwn').onclick=()=>{if(toggleOwned(f)){$('#detail').close();openDetail(f)}};$('#detailWish').onclick=()=>{if(toggleWished(f)){$('#detail').close();openDetail(f)}};}
function clearFilters(){document.querySelectorAll('.filters input').forEach(i=>i.checked=false);$('#search').value='';render()}
function setView(view){const list=view==='list';$('#catalogue').classList.toggle('list',list);$('#listView').classList.toggle('active',list);$('#gridView').classList.toggle('active',!list);$('#listView').setAttribute('aria-pressed',list);$('#gridView').setAttribute('aria-pressed',!list);localStorage.setItem('minifig-view',view)}
document.querySelectorAll('.currency-toggle button').forEach(button=>button.onclick=()=>{totalCurrency=button.dataset.currency;localStorage.setItem('minifig-total-currency',totalCurrency);updateStats()});
$('#search').addEventListener('input',render);$('#sort').addEventListener('change',render);$('#filterToggle').onclick=()=>{const open=$('#filters').classList.toggle('open');$('#filterToggle').setAttribute('aria-expanded',open)};$('#clearFilters').onclick=clearFilters;$('#resetEmpty').onclick=clearFilters;$('#gridView').onclick=()=>setView('grid');$('#listView').onclick=()=>setView('list');$('#closeDetail').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});$('#theme').onclick=()=>{const dark=document.body.classList.toggle('dark');localStorage.setItem('minifig-theme',dark?'dark':'light');$('#theme').setAttribute('aria-pressed',dark)};const savedTheme=localStorage.getItem('minifig-theme')==='dark';document.body.classList.toggle('dark',savedTheme);$('#theme').setAttribute('aria-pressed',savedTheme);setView(localStorage.getItem('minifig-view')||'grid');load();
