import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { browserLocalPersistence, getAuth, GoogleAuthProvider, onAuthStateChanged, setPersistence, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { addDoc, collection, doc, getDocs, getFirestore, limit, orderBy, query, serverTimestamp, setDoc, where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDUOiBJMfjHyFISy_U7rA7ldKKnoZ05QvQ',authDomain:'custom-figures-collector.firebaseapp.com',projectId:'custom-figures-collector',storageBucket:'custom-figures-collector.firebasestorage.app',messagingSenderId:'725550496124',appId:'1:725550496124:web:6e2910da4ee2f60bcc8cf9'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=selector=>document.querySelector(selector),authButton=$('#authButton'),authStatus=$('#authStatus'),workspace=$('#adminWorkspace'),accessPanel=$('#accessPanel'),form=$('#premiumForm'),formStatus=$('#formStatus'),tbody=$('#premiumUsers'),auditEntries=$('#auditEntries');
let users=[];
const setStatus=(element,message,error=false)=>{element.textContent=message;element.classList.toggle('error',error)};
const displayDate=value=>{const date=value?.toDate?.()||value;if(!date)return'—';return new Date(date).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})};
function renderUsers(){const query=$('#userSearch').value.trim().toLowerCase(),visible=users.filter(user=>!query||user.email.toLowerCase().includes(query));tbody.replaceChildren(...visible.map(user=>{const row=document.createElement('tr');row.innerHTML=`<td>${user.email}</td><td><span class="status ${user.status}">${user.status}</span></td><td>${user.licenseType}</td><td>${displayDate(user.updatedAt)}</td><td><button type="button" class="edit-user">Edit</button></td>`;row.querySelector('button').onclick=()=>{$('#premiumEmail').value=user.email;$('#premiumStatus').value=user.status;$('#premiumNotes').value=user.notes||'';scrollTo({top:document.querySelector('.editor').offsetTop-20,behavior:'smooth'})};return row}));$('#emptyUsers').hidden=visible.length>0;$('#premiumCount').textContent=users.length;$('#activeCount').textContent=users.filter(user=>user.status==='active').length;$('#inactiveCount').textContent=users.filter(user=>user.status!=='active').length}
function renderAudit(entries=[]){auditEntries.replaceChildren(...entries.map(entry=>{const item=document.createElement('article');item.className='audit-entry';item.innerHTML=`<time>${displayDate(entry.createdAt)}</time><span><strong>${entry.action.replaceAll('-',' ')}</strong><br><small>${entry.targetEmail||entry.targetUid}</small></span><small>${entry.administratorEmail||entry.administratorUid}</small>`;return item}));if(!entries.length)auditEntries.textContent='No administrative changes yet.'}
async function loadData(){const [entitlements,audit]=await Promise.all([getDocs(query(collection(db,'premiumEntitlements'),orderBy('updatedAt','desc'))),getDocs(query(collection(db,'premiumAuditLog'),orderBy('createdAt','desc'),limit(100)))]);users=entitlements.docs.map(item=>({uid:item.id,...item.data()}));renderUsers();renderAudit(audit.docs.map(item=>({id:item.id,...item.data()})))}
async function authorize(user){authButton.textContent='Sign out';setStatus(authStatus,`Checking administrator access for ${user.email}…`);try{if(user.email?.toLowerCase()!=='mreizinho@gmail.com'||!user.emailVerified)throw Error('Administrator access was not granted.');accessPanel.hidden=true;workspace.hidden=false;await loadData()}catch(error){workspace.hidden=true;accessPanel.hidden=false;setStatus(authStatus,error.message||'Administrator access was denied.',true)}}
authButton.onclick=async()=>{try{if(auth.currentUser){await signOut(auth);return}await signInWithPopup(auth,provider)}catch(error){setStatus(authStatus,error.message,true)}};
form.onsubmit=async event=>{event.preventDefault();const button=$('#savePremium'),email=$('#premiumEmail').value.trim().toLowerCase(),status=$('#premiumStatus').value,notes=$('#premiumNotes').value.trim();button.disabled=true;setStatus(formStatus,'Saving…');try{const profiles=await getDocs(query(collection(db,'premiumProfiles'),where('email','==',email),limit(1)));if(profiles.empty)throw Error('This customer must sign in once before premium access can be granted.');const profile=profiles.docs[0],now=serverTimestamp(),administrator=auth.currentUser;await setDoc(doc(db,'premiumEntitlements',profile.id),{email,tier:'premium',status,licenseType:'lifetime',notes,updatedAt:now,updatedBy:administrator.uid},{merge:true});await addDoc(collection(db,'premiumAuditLog'),{action:'set-entitlement',targetUid:profile.id,targetEmail:email,administratorUid:administrator.uid,administratorEmail:administrator.email||'',status,createdAt:serverTimestamp()});setStatus(formStatus,`${email} updated.`);form.reset();await loadData()}catch(error){setStatus(formStatus,error.message,true)}finally{button.disabled=false}};
$('#userSearch').oninput=renderUsers;$('#refreshData').onclick=()=>loadData().catch(error=>setStatus(authStatus,error.message,true));
await setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,user=>{if(user)authorize(user);else{authButton.textContent='Sign in';workspace.hidden=true;accessPanel.hidden=false;setStatus(authStatus,'Sign in with the administrator account.')}});
